### ISSUE TITLE
Alaska looks totally wrong

### ISSUE THREAD

**Issue by dex2000** [Microsoft/USBuildingFootprints#23] opened 2018-07-03 22:24 UTC
I have take a look at the data in Alaska and could not find any really building (on esri-imagery, bing is most time only great pixels). 
Most of the "buildings" are in nowhere [1]. Buildings with real positions have wrong geometry [2] 

Please review.

[1] ![hc_011](https://user-images.githubusercontent.com/5686458/42247232-26ba3768-7f20-11e8-8df3-1b497b222f99.png)
or: ![hc_012](https://user-images.githubusercontent.com/5686458/42247292-7c849224-7f20-11e8-928a-7212f09553f4.png)

[2] ![building](https://user-images.githubusercontent.com/5686458/42247080-8142c39a-7f1f-11e8-8c5b-0ad3207c0125.png)

**Comment by nitrif** [comment] 2018-07-04 13:32
Thanks for pointing this.
We expect false positive rate to be around 1-2%, depending on the image quality. If that is not the case on some localities, we'll investigate the cause. It would be helpful to share problematic location coordinates as well.
We'll create the Alaska sample to verify.

**Comment by dex2000** [comment] 2018-07-04 14:11
Try
```
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-162.29829180746921,67.065484829532025],[-162.2980605801788,67.065396667337126],[-162.29800845420311,67.065301229972675],[-162.2979595254927,67.06530528803566],[-162.29783793537931,67.06525893124703],[-162.29755610936309,67.065282305443048],[-162.29751287645109,67.065348800165339],[-162.297700728894,67.0654204245917],[-162.29771731974961,67.065450800653821],[-162.2979811329144,67.065428920567427],[-162.29795371084811,67.0654710970595],[-162.2980093464879,67.065572959534876],[-162.298563989114,67.065627718481821],[-162.298737866893,67.065694009147251],[-162.29883287103439,67.06570338871056],[-162.29890326992549,67.065832322097251],[-162.2991248142952,67.065916784840681],[-162.29952898740169,67.065956698650567],[-162.299612908389,67.065923274178829],[-162.29959083897711,67.065906853710757],[-162.29980195356711,67.065889344659752],[-162.2999064910953,67.065728607562434],[-162.2996024569556,67.065502391992752],[-162.29949380373259,67.065491664794479],[-162.29952192828731,67.065543157638245],[-162.29944726900649,67.065558394436181],[-162.29941046985221,67.065614993033677],[-162.2994317410344,67.06563081977977],[-162.2993125534058,67.065619052594741],[-162.29932813922451,67.065595087611385],[-162.2986314195625,67.06552628252004],[-162.29861914115389,67.065517146776457],[-162.29829180746921,67.065484829532025]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-147.9482747051602,64.906218866076813],[-147.948050744154,64.906177205005861],[-147.948031487887,64.906195823896454],[-147.94806199829449,64.9062015003268],[-147.94804324990179,64.906219625245214],[-147.94807698983,64.906225902518955],[-147.94809376470781,64.906209685491049],[-147.94825346703479,64.9062393979181],[-147.9482747051602,64.906218866076813]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-147.69377449693769,64.837012191270077],[-147.6939021046104,64.837017317840335],[-147.69392896175489,64.836896367230509],[-147.693964910762,64.836897811469044],[-147.69398512651679,64.836806837308927],[-147.69382155392341,64.836800270683341],[-147.69377449693769,64.837012191270077]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-146.467389322716,64.782933366923331],[-146.46767354634051,64.782935528089865],[-146.46767569979431,64.7828841205833],[-146.46772290870371,64.7828844795489],[-146.46772419571059,64.782853634959849],[-146.46739276824209,64.782851114859227],[-146.467389322716,64.782933366923331]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-150.16889830853819,62.001307084239272],[-150.16875519624941,62.001305692403918],[-150.16875150574421,62.001389321158157],[-150.1690018733469,62.0013917478698],[-150.16900458574969,62.001330075094337],[-150.1688973431051,62.001329035632807],[-150.16889830853819,62.001307084239272]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-149.93070831815561,61.1164319317414],[-149.93050118789631,61.116441966189512],[-149.9305078415552,61.116474033597633],[-149.9303883433287,61.116479822694977],[-149.93041638359591,61.116614962798742],[-149.9307430143501,61.1165991502635],[-149.93070831815561,61.1164319317414]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-160.3398031126687,60.6635867767048],[-160.3395928806558,60.663599255258617],[-160.33948745433781,60.663627987860806],[-160.33949379201209,60.663653602757222],[-160.3394567486161,60.6636797219202],[-160.3394020208884,60.6636946372323],[-160.33941151409121,60.663733005700763],[-160.33946491202991,60.663780041691638],[-160.33944392416291,60.663820852409039],[-160.33947707474539,60.6638249446284],[-160.33954840418,60.663820708375212],[-160.33959033817769,60.663834983937022],[-160.33961899468241,60.663838521390772],[-160.33963896333759,60.663833079909992],[-160.3396319434022,60.663804691293407],[-160.33963828383281,60.663792362382679],[-160.33970121495241,60.663788627059333],[-160.3397364287228,60.663800614871192],[-160.33979319237369,60.663785144746143],[-160.33999048144659,60.663773427737581],[-160.34005213428191,60.663756625120413],[-160.34006770928971,60.663755700119211],[-160.3400983051659,60.6637661158738],[-160.34009380338429,60.663747921146651],[-160.3401219580181,60.66372807146071],[-160.3401376627838,60.663697533602758],[-160.340132635534,60.663677215061149],[-160.33999004496641,60.663659613117687],[-160.33994486899121,60.663644233807723],[-160.33992784428321,60.663629239291851],[-160.3398031126687,60.6635867767048]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-146.59057025695469,64.829736935695465],[-146.5908955968942,64.829810604559057],[-146.5912786296413,64.829815119620179],[-146.59127169230979,64.829921576023679],[-146.59164168070819,64.830005343328082],[-146.5931613879221,64.830023256991254],[-146.59315832015531,64.83007033290987],[-146.59312777992361,64.830078288242376],[-146.59324555806779,64.830104953702],[-146.5932411042738,64.830173126290148],[-146.593350474596,64.830249073322662],[-146.59399911645329,64.830256719169626],[-146.59400761504719,64.830126306071634],[-146.59412767018071,64.830095033315558],[-146.5941341190543,64.829996073164992],[-146.59404343812179,64.829933103516169],[-146.59370402191951,64.829856257720166],[-146.59356837396061,64.829854658750207],[-146.59323247368641,64.829621404639255],[-146.5928453435738,64.829616841246946],[-146.59263585739041,64.8296714105406],[-146.59215367899421,64.829665726753475],[-146.59212511029381,64.829645888165444],[-146.59153396006531,64.829799877108854],[-146.59130528558521,64.829797181569617],[-146.59127622051059,64.829769769308513],[-146.59090565505679,64.829512442258519],[-146.5905950662231,64.829442122055823],[-146.59058937190221,64.829443605387013],[-146.59057025695469,64.829736935695465]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-150.33138971341239,61.470339006701423],[-150.3311289445214,61.47007288856183],[-150.33117265786689,61.469959376672158],[-150.33116853286771,61.469948030466448],[-150.3309801005683,61.469755701838253],[-150.33074236183009,61.469775418800111],[-150.33097368638619,61.46964079284092],[-150.3308850420525,61.469396964705638],[-150.3306727299472,61.469255637445407],[-150.33053043564269,61.469243136773578],[-150.33043603176481,61.469298078589269],[-150.33059221947269,61.4697276939214],[-150.3307113595701,61.469738160314591],[-150.33072469654431,61.4697748451718],[-150.3307746476122,61.469794424946052],[-150.33064572529679,61.469823243494048],[-150.33062555467839,61.469875621485933],[-150.33050298509511,61.4698275768752],[-150.33046951433991,61.469835057609778],[-150.33048250430471,61.469801325924209],[-150.33041416144309,61.469795322053351],[-150.3302799356548,61.469742708324283],[-150.33002455158569,61.469763897254417],[-150.3299662431001,61.469797831470487],[-150.3302399404314,61.470077145663453],[-150.3301952893377,61.470080848783361],[-150.33019272607351,61.470078232927392],[-150.32988768823071,61.470146418656412],[-150.3299256812933,61.470185196933713],[-150.32986883835289,61.470189911162912],[-150.3298630493978,61.47020494344644],[-150.33138971341239,61.470339006701423]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-131.1312341502877,55.742333764107222],[-131.13126597143389,55.742335683495241],[-131.13127279088729,55.742299858246319],[-131.1312409697411,55.742297938856538],[-131.1312341502877,55.742333764107222]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-134.4472089078015,58.3159542858518],[-134.44731382428171,58.315919169785388],[-134.4472877554775,58.31589768324028],[-134.44732781576789,58.315884276317618],[-134.44725298877091,58.315822601983228],[-134.447108013271,58.315871126125572],[-134.4472089078015,58.3159542858518]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-149.78195645286081,61.182308717253562],[-149.78222848228171,61.182397580591847],[-149.78235180067179,61.182309868876366],[-149.78207977125089,61.182221005290813],[-149.78195645286081,61.182308717253562]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-134.5788483688338,58.365280756048428],[-134.57870873331521,58.365449509110491],[-134.57885670733191,58.3654831928699],[-134.57899632768229,58.365314431084641],[-134.5788483688338,58.365280756048428]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-131.706714344932,55.434133589051143],[-131.70671268580429,55.43428138502631],[-131.70672603481049,55.434299182921038],[-131.70679355341369,55.434310529092478],[-131.70681321328809,55.434336741087087],[-131.7068653252731,55.43433692939081],[-131.70690260013549,55.434327930280872],[-131.70690251468741,55.43433554202042],[-131.70694761568259,55.434335704990339],[-131.70696660166229,55.4343610226471],[-131.70702915235771,55.434256948937062],[-131.70704559860249,55.434252979036053],[-131.7070461124832,55.434207202302382],[-131.7070748441362,55.434200266861048],[-131.70709030134279,55.434170665807152],[-131.70712599515281,55.434162049784973],[-131.7071261348236,55.434149469579438],[-131.70713880975379,55.434151600051173],[-131.7072090050184,55.43415185091164],[-131.707219120123,55.434132475558549],[-131.7071753573843,55.4341251214113],[-131.7071317709146,55.434135644359372],[-131.70710992443111,55.434106516866827],[-131.70705957150241,55.43409805525971],[-131.7069353643048,55.434097611373367],[-131.70692849883861,55.4340884562682],[-131.70689283352431,55.434088328809],[-131.706714344932,55.434133589051143]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-147.1460003049022,64.680315864520082],[-147.14598926769591,64.680523381088818],[-147.1461645114349,64.680525080584],[-147.1461626876897,64.68055947549432],[-147.14627796340051,64.680560593424474],[-147.1462770197183,64.680578390774059],[-147.14660139969229,64.680581546279413],[-147.14661517089741,64.680321827470479],[-147.1460003049022,64.680315864520082]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-131.5426047042728,55.272192528550782],[-131.54246549044029,55.272174600074777],[-131.54228277987221,55.272197773262008],[-131.5422527612678,55.272273419746611],[-131.54229954257781,55.272393123678981],[-131.542486773382,55.272420963572337],[-131.54261189936659,55.272405093930338],[-131.542650133799,55.272308773783088],[-131.5426047042728,55.272192528550782]]]}},
    {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-131.561281979084,55.166320473318358],[-131.561281979084,55.1664859362627],[-131.5613329410553,55.1664859362627],[-131.5613329410553,55.166502788931467],[-131.5613963349002,55.166502788931467],[-131.5613963390301,55.166469083586811],[-131.56148850917819,55.166469083586811],[-131.56148850917819,55.166423121707282],[-131.56157433986661,55.166423121707282],[-131.56157433986661,55.166484404201547],[-131.5617057681084,55.166484404201547],[-131.5617057681084,55.166320473318358],[-131.561281979084,55.166320473318358]]]}}
```

3 good buildings, and a forth with wrong geometry. The rest is nothing.
(This list is a random-extract of parts from alaska.json)

**Comment by gboeing** [comment] 2018-07-05 17:22
The false positive rate in Alaska is much higher than 2%. For example see the overview (footprints in black):

![ak1](https://user-images.githubusercontent.com/4977197/42337863-de724b62-803c-11e8-9d91-f8bc7e6025b5.jpg)

Other than Anchorage, most buildings footprints in the data set are located where there is no development. Zooming in looks like:

![ak2](https://user-images.githubusercontent.com/4977197/42337866-dfe3b9f4-803c-11e8-951b-fc8d95a4ecff.jpg)

And:

![ak3](https://user-images.githubusercontent.com/4977197/42337873-e1b719c4-803c-11e8-89c2-25f6d5d86528.jpg)

These are in the middle of forests.

**Comment by nitrif** [comment] 2018-07-06 08:39
Thanks @dex2000 and @gboeing. We have confirmed the problem on the verification sample and started working on this.

**Comment by nitrif** [comment] 2018-07-13 16:31
Fixed in the latest release.

**Closed by nitrif** 2018-07-13 16:31 UTC
