### ISSUE TITLE
Dates of imagery used

### ISSUE THREAD

**Issue by jonjab** [Microsoft/USBuildingFootprints#46] opened 2018-10-24 21:41 UTC
One thing that would be helpful in the ReadMe would be to tell us what the dates of imagery acquisition (when the plane flew) are.  Are these datasets 2017 US buildings or 2018 US buildings?  Or earlier?

**Comment by ekrose** [comment] 2018-11-30 15:36
I agree. I realize it is difficult to pinpoint the vintage, but any rough guidance by state would be very useful.

**Comment by mshi1992307** [comment] 2019-03-11 16:48
Same here. Would be really helpful to know the date of the imagery acquired.

**Comment by nmpeterson** [comment] 2019-03-12 14:42
Perhaps it would be possible to create secondary geojson files containing (presumably) very large polygons, where each one would represent a contiguous area of imagery collected in a particular year?

**Comment by IoTGirl** [comment] 2019-03-13 19:41
Duplicate of #9

**Closed by IoTGirl** 2019-03-13 19:41 UTC
