### ISSUE TITLE
Random shapes in the Upper Peninsula (MI)

### ISSUE THREAD

**Issue by chrisbnyc** [Microsoft/USBuildingFootprints#24] opened 2018-07-03 22:41 UTC
There seems to be spurious content in the Michigan file.

<img width="576" alt="upperpen" src="https://user-images.githubusercontent.com/1864838/42247792-4c96dc46-7ef0-11e8-8737-7d843c8895dc.png">

What's odd is I can't say where they are actually from!  It doesn't appear to be extra bits of Canada stuck in.

**Comment by nitrif** [comment] 2018-07-04 12:44
Thanks. We'll investigate this.

**Comment by nitrif** [comment] 2018-07-04 13:21
There are few thousand false positive footprints on Lake Superior. These are mainly caused by the detection network not being tuned on vast water surface variety. For the next update we'll set up the filter triggering on intersection with known water polygons. This should nail similar issues.

**Comment by gboeing** [comment] 2018-07-04 14:15
@nitrif fantastic, thanks. Do you have a sense of data update release timing/frequency?

**Comment by nitrif** [comment] 2018-07-05 15:18
This could be classified into filtering problem, which is fairly easy, and we will try to fix this frequently. We will wait for several more days in order to include fixes for more initial issues in the same batch.
Algo updates will be rare.

**Comment by nitrif** [comment] 2018-07-13 16:32
Fixed in the latest release.

**Closed by nitrif** 2018-07-13 16:32 UTC
