### ISSUE TITLE
Really a GeoJSON?

### ISSUE THREAD

**Issue by antifa-ev** [Microsoft/USBuildingFootprints#30] opened 2018-07-13 15:20 UTC
When converting the json with [tippecanoe](https://github.com/mapbox/tippecanoe) I'm getting an error for every line.

Code line:

`tippecanoe -o Wyoming.mbtiles -zg --drop-densest-as-needed Wyoming.json `

Error:

```
Wyoming.json:376881: feature without properties hash
In JSON object {"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-104.4228260023874,41.151506633415309],[-104.4229350980483,41.151537892349722],[-104.4229579082815,41.151492748294707],[-104.4230375721159,41.151515570002118],[-104.4230714466938,41.151448528312251],[-104.4228826937695,41.151394455225308],[-104.4228260023874,41.151506633415309]]]}}
```

**Comment by nitrif** [comment] 2018-07-13 16:31
Could you please check the latest release?

**Comment by jgravois** [comment] 2018-07-13 20:34
duplicate of #15

**Closed** 2018-07-13 22:17 UTC
